version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usertest
    ports:
      - "5431:5432"

  test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mockusertest
    ports:
      - "5433:5432"
    volumes:
      - ./mockdata:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: userService
    depends_on:
      - db
      - test-db
    ports:
      - "8080:8080"
    environment:
      DSN_DB: "host=db port=5432 user=postgres password=postgres dbname=usertest sslmode=disable"
      DSN_TEST_DB: "host=test-db port=5432 user=postgres password=postgres dbname=mockusertest sslmode=disable"
  adminer:
    image: adminer
    restart: always
    environment:
        ADMINER_DESIGN: dracula
    ports:
      - "3333:8080"